### ISSUE TITLE
dropdown组件有考虑做成key-value形式的组件嘛

### ISSUE THREAD

**Issue by Pixel-Daze** [jlianphoto/iver#1]
现在的组件内部直接是获取的name作为渲染值，在生产过程中一般对应的都是相应的编码
{name:"广州市",value:"002"}
类似这种编码格式，可以考虑扩展一下组件

**Comment by jlianphoto** [comment]
我是觉得这类组件的数据量不会太大，所以没有那么搞，不过你可以pr一波~
